##### config.yml

data:
    dat_order: [D, Ds, Pi]
    data: [["../dataDDspi/dat/B0toD0Dspi_Data_Run1.dat"], ["../dataDDspi/dat/B0toD0Dspi_Data_Run2.dat"],["../dataDDspi/dat/B0toD0_K3piDspi_Data_Run1.dat"], ["../dataDDspi/dat/B0toD0_K3piDspi_Data_Run2.dat"]]
    #data_weight: ["../dataDDspi/dat/B0toD0Dspi_Data_Run1_Weight.dat", "../dataDDspi/dat/B0toD0Dspi_Data_Run2_Weight.dat","../dataDDspi/dat/B0toD0_K3piDspi_Data_Run1_Weight.dat", "../dataDDspi/dat/B0toD0_K3piDspi_Data_Run2_Weight.dat"]
    #phsp: [["../dataDDspi/dat/B0toD0Dspi_MC_Noeff.dat"],["../dataDDspi/dat/B0toD0Dspi_MC_Noeff.dat"],["../dataDDspi/dat/B0toD0Dspi_MC_Noeff.dat"],["../dataDDspi/dat/B0toD0Dspi_MC_Noeff.dat"]]
    phsp: [["../dataDDspi/dat/B0toD0Dspi_MC_Run1.dat"], ["../dataDDspi/dat/B0toD0Dspi_MC_Run2.dat"],["../dataDDspi/dat/B0toD0_K3piDspi_MC_Run1.dat"], ["../dataDDspi/dat/B0toD0_K3piDspi_MC_Run2.dat"]]
    phsp_weight: ["../dataDDspi/dat/B0toD0Dspi_MC_Run1_Weight.dat", "../dataDDspi/dat/B0toD0Dspi_MC_Run2_Weight.dat","../dataDDspi/dat/B0toD0_K3piDspi_MC_Run1_Weight.dat", "../dataDDspi/dat/B0toD0_K3piDspi_MC_Run2_Weight.dat"]
    phsp_noeff: ["../dataDDspi/dat/B0toD0Dspi_MC_Noeff.dat"]
    bg: [["../dataDDspi/dat/B0toD0Dspi_BSB_Run1.dat"], ["../dataDDspi/dat/B0toD0Dspi_BSB_Run2.dat"],["../dataDDspi/dat/B0toD0_K3piDspi_BSB_Run1.dat"], ["../dataDDspi/dat/B0toD0_K3piDspi_BSB_Run2.dat"]]
    bg_weight: [0.131039, 0.103967, 0.143792, 0.106173]
    cached_amp: True


decay:
    B:
        - [BzR_DPi, Ds, p_break: True]
        - [D1_2010, Ds, p_break: True, curve_style: "b--"]
        - [BzR_DDs, Pi, p_break: True]
        - [BzR_DsPi, D, p_break: True]
        - [Z0, D, p_break: True, curve_style: "purple"]
        - [Z1, D, p_break: True, curve_style: "magenta"]
        - [Z2, D, p_break: True, curve_style: "cyan"]
        - [Z3, D, p_break: True, curve_style: "cyan"]
        - [Z0hist, D, p_break: True, curve_style: "purple"]
        - [Z1hist, D, p_break: True, curve_style: "magenta"]
        - [NR_DPi0, Ds, p_break: True, curve_style: "g-"]
        - [NR_DPi1, Ds, p_break: True, curve_style: "b-"]
        - [DPi_S, Ds, p_break: True, curve_style: "g-"]
        - [DPi_P, Ds, p_break: True, curve_style: "b-"]

    BzR_DPi: [D, Pi]
    D1_2010: [D, Pi]
    BzR_DDs: [D, Ds]
    BzR_DsPi: [Ds, Pi]
    Z0: [Ds, Pi]
    Z1: [Ds, Pi]
    Z2: [Ds, Pi]
    Z3: [Ds, Pi]
    Z0hist: [Ds, Pi]
    Z1hist: [Ds, Pi]
    NR_DPi0: [D, Pi]
    NR_DPi1: [D, Pi]
    DPi_S: [D, Pi]
    DPi_P: [D, Pi]


particle:
    $top:
        B: # Bz = 5.27963
            J: 0
            P: -1
    # final particles
    $finals:
        D: # Dz = 1.86483
            J: 0
            P: -1
        Ds: # Dsp = 1.96834
            J: 0
            P: -1
        Pi: # pim = 0.13957039
            J: 0
            P: -1
    $include: Resonances.sample.yml
    BzR_DDs: []
        #- DDs
    BzR_DsPi: []
        #- DsPi
    Z0: {J: 0, Par: 1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.7, m_max: 3.2, g_min: 0.01, g_max: 0.5,}
    Z1: [] #{J: 1, Par: -1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.7, m_max: 3.2, g_min: 0.01, g_max: 0.5,}
    Z2: [] #{J: 2, Par: 1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.1, m_max: 3.4, g_min: 0.001, g_max: 0.5,}
    Z3: [] #{J: 3, Par: -1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.1, m_max: 3.4, g_min: 0.001, g_max: 0.5,}
    BzR_DPi:
        - D2_2460
        - D1_2600
        #- D0_2300
        #- D0_2900
        #- D3_2750
        #- D1_2760
        #- DJ_2640
        #- DJ_3000
        #- Dstar
    D1_2010: {J: 1, Par: -1, m0: 2.01026, g0: 0.0000834}

    NR_DPi0: [] #{display: "NR(0+)(D0pi-)", J: 0, P: 1, mass: 2.4, model: exp2}
    NR_DPi1: [] #{display: "NR(1-)(D0pi-)", J: 1, P: -1, mass: 2.4, model: one}
    DPi_S: {J: 0, P: 1, mass: 2.65, fix_idx: 4, model: spline_c, points: [1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 3.0, 3.2, 3.4]}
        #model: interp_hist, points: [1.95, 2.0, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4, 2.42, 2.44, 2.46, 2.48, 2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.85, 2.95, 3.05, 3.15, 3.25, 3.35]} #max_m: 3.35, min_m: 1.95, interp_N: 29}
    DPi_P: [] #{J: 1, P: -1, mass: 2.65, #model: interp_hist, max_m: 3.4, min_m: 2.0, interp_N: 15}
                #model: spline_c, points: [1.95, 2.05, 2.15, 2.25, 2.35, 2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05, 3.15, 3.25, 3.4]}
    Z0hist: [] #{J: 0, P: 1, mass: 2.970, model: interp_hist, points: [2.673,2.740,2.807,2.873,2.940,3.007,3.073,3.140,3.207]}#[2.693,2.759,2.824,2.890,2.956,3.021,3.087,3.153,3.219]}
    Z1hist: [] #{J: 1, P: -1, mass: 2.879, model: interp_hist, points: [2.525,2.614,2.702,2.791,2.879,2.968,3.056,3.145,3.234]}#[2.437,2.544,2.652,2.760,2.868,2.975,3.083,3.191,3.299]}

# constrains for params [WIP]
constrains:
    particle: null
    decay: {fix_chain_idx: 0, fix_chain_val: 1}


plot:
    # plot configuration TODO
    config:
        bins: 100
    # invariant mass
    mass:
        BzR_DDs:
            display: "$M_{\\bar D^0D_s^+}$"
            #legend: False
            #yscale: log
            #trans: x*x
        BzR_DPi:
            display: "$M_{\\bar D^0\\pi^-}$"
            #legend: False
            #yscale: log
            #trans: x*x
        BzR_DsPi:
            display: "$M_{D_s^+\\pi^-}$"
            #legend: False
            #yscale: log
            #trans: x*x
    angle:
        BzR_DPi/D:
            cos(beta):
                display: "$\\cos(\\theta^{\\bar D^0\\pi^-}_{\\bar D^0})$"
                range: [-1, 1]
                yscale: log
        BzR_DsPi/Ds:
            cos(beta):
                display: "$\\cos(\\theta^{D_s^+\\pi^-}_{D_s^+})$"
                range: [-1, 1]
                yscale: log
        BzR_DDs/D:
            cos(beta):
                display: "$\\cos(\\theta^{\\bar D^0D_s^+}_{\\bar D^0})$"
                range: [-1, 1]
                yscale: log
    # 2D plot
    2Dplot:
        m_BzR_DPi & m_BzR_DsPi:
            display: "$M_{\\bar D^0\\pi^-}^2$ vs $M_{D_s^+\\pi^-}^2$"
            trans: x*x
            plot_figs: [""]
    #    m_BzR_DsPi & m_BzR_DDs:
    #        display: "$M_{D_s^+\\pi^-}^2$ vs $M_{\\bar D^0D_s^+}^2$"
    #        plot_figs: ["data", "sideband"]
    #    m_BzR_DDs & m_BzR_DPi:
    #        display: "$M_{\\bar D^0D_s^+}^2$ vs $M_{\\bar D^0\\pi^-}^2$"
    #        plot_figs: ["data", "sideband", "fitted"]



##### configC.yml

data:
    model: cfit
    dat_order: [D, Ds, Pi]
    bg_frac: [0.09936606635, 0.07730492154, 0.09610219095, 0.1232115413]
    data_bg_value: ["../dataDDspi/dat_cfit/B0toD0Dspi_Data_Run1_value.dat", "../dataDDspi/dat_cfit/B0toD0Dspi_Data_Run2_value.dat", "../dataDDspi/dat_cfit/B0toD0_K3piDspi_Data_Run1_value.dat",  "../dataDDspi/dat_cfit/B0toD0_K3piDspi_Data_Run2_value.dat"]
    phsp_bg_value: ["../dataDDspi/dat_cfit/B0toD0Dspi_MC_Run1_value.dat", "../dataDDspi/dat_cfit/B0toD0Dspi_MC_Run2_value.dat", "../dataDDspi/dat_cfit/B0toD0_K3piDspi_MC_Run1_value.dat",  "../dataDDspi/dat_cfit/B0toD0_K3piDspi_MC_Run2_value.dat"]
    #data_eff_value: "toy_data/data_eff_value.dat"
    #phsp_eff_value: "toy_data/phsp_eff_value.dat"
    
    data: [["../dataDDspi/dat/B0toD0Dspi_Data_Run1.dat"], ["../dataDDspi/dat/B0toD0Dspi_Data_Run2.dat"],["../dataDDspi/dat/B0toD0_K3piDspi_Data_Run1.dat"], ["../dataDDspi/dat/B0toD0_K3piDspi_Data_Run2.dat"]]
    phsp: [["../dataDDspi/dat/B0toD0Dspi_MC_Run1.dat"], ["../dataDDspi/dat/B0toD0Dspi_MC_Run2.dat"],["../dataDDspi/dat/B0toD0_K3piDspi_MC_Run1.dat"], ["../dataDDspi/dat/B0toD0_K3piDspi_MC_Run2.dat"]]
    phsp_weight: ["../dataDDspi/dat/B0toD0Dspi_MC_Run1_Weight.dat", "../dataDDspi/dat/B0toD0Dspi_MC_Run2_Weight.dat","../dataDDspi/dat/B0toD0_K3piDspi_MC_Run1_Weight.dat", "../dataDDspi/dat/B0toD0_K3piDspi_MC_Run2_Weight.dat"]
    phsp_noeff: ["../dataDDspi/dat/B0toD0Dspi_MC_Noeff.dat"]
    cached_amp: True
    bg: [["../dataDDspi/dat_cfit/B0toD0Dspi_Run1_BKGsample.dat"], ["../dataDDspi/dat_cfit/B0toD0Dspi_Run2_BKGsample.dat"],["../dataDDspi/dat_cfit/B0toD0_K3piDspi_Run1_BKGsample.dat"], ["../dataDDspi/dat_cfit/B0toD0_K3piDspi_Run2_BKGsample.dat"]]
    bg_weight: [0.03433336244541484, 0.037363140625, 0.029742357698289267, 0.030020903705865187] # note the sample data has changed. need to scp from lxplus.cern.ch










##### config_Bp.yml

data:
    dat_order: [D, Ds, Pi]
    data: [["../dataDDspi/dat/BptoDmDspi_Data_Run1.dat"], ["../dataDDspi/dat/BptoDmDspi_Data_Run2.dat"]]
    #data_weight: ["../dataDDspi/dat/BptoDmDspi_Data_Run1_Weight.dat", "../dataDDspi/dat/BptoDmDspi_Data_Run2_Weight.dat"]
    #phsp: [["../dataDDspi/dat/BptoDmDspi_MC_Noeff.dat"], ["../dataDDspi/dat/BptoDmDspi_MC_Noeff.dat"]]
    phsp: [["../dataDDspi/dat/BptoDmDspi_MC_Run1.dat"], ["../dataDDspi/dat/BptoDmDspi_MC_Run2.dat"]]
    phsp_weight: ["../dataDDspi/dat/BptoDmDspi_MC_Run1_Weight.dat", "../dataDDspi/dat/BptoDmDspi_MC_Run2_Weight.dat"]
    phsp_noeff: ["../dataDDspi/dat/BptoDmDspi_MC_Noeff.dat"]
    bg: [["../dataDDspi/dat/BptoDmDspi_BSB_Run1.dat"], ["../dataDDspi/dat/BptoDmDspi_BSB_Run2.dat"]]
    bg_weight: [0.0861442, 0.0554937]
    cached_amp: True


decay:
    B:
        - [BpR_DPi, Ds, p_break: True]
        - [D1_2007, Ds, p_break: True, curve_style: "b--"]
        - [BpR_DDs, Pi, p_break: True]
        - [BpR_DsPi, D, p_break: True]
        - [Z0, D, p_break: True, curve_style: "purple"]
        - [Z1, D, p_break: True, curve_style: "magenta"]
        - [Z2, D, p_break: True, curve_style: "cyan"]
        - [Z3, D, p_break: True, curve_style: "cyan"]
        - [Z0hist, D, p_break: True, curve_style: "purple"]
        - [Z1hist, D, p_break: True, curve_style: "magenta"]
        - [NR_DPi0, Ds, p_break: True, curve_style: "g-"]
        - [NR_DPi1, Ds, p_break: True, curve_style: "b-"]
        - [DPi_S, Ds, p_break: True, curve_style: "g-"]
        - [DPi_P, Ds, p_break: True, curve_style: "b-"]

    BpR_DPi: [D, Pi]
    D1_2007: [D, Pi, has_barrier_factor: False]
    BpR_DDs: [D, Ds]
    BpR_DsPi: [Ds, Pi]
    Z0: [Ds, Pi]
    Z1: [Ds, Pi]
    Z2: [Ds, Pi]
    Z3: [Ds, Pi]
    Z0hist: [Ds, Pi]
    Z1hist: [Ds, Pi]
    NR_DPi0: [D, Pi]
    NR_DPi1: [D, Pi]
    DPi_S: [D, Pi]
    DPi_P: [D, Pi]


particle:
    $top:
        B: # Bp = 5.27934
            J: 0
            P: -1
    # final particles
    $finals:
        D: # Dm = 1.86965
            J: 0
            P: -1
        Ds: # Dsp = 1.96834
            J: 0
            P: -1
        Pi: # pip = 0.13957039
            J: 0
            P: -1
    $include: Resonances.sample.yml
    BpR_DDs: []
        #- DDs
    BpR_DsPi: []
        #- DsPi
    Z0: {J: 0, Par: 1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.7, m_max: 3.2, g_min: 0.01, g_max: 0.5,}
    Z1: [] #{J: 1, Par: -1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.7, m_max: 3.2, g_min: 0.01, g_max: 0.5,}
    Z2: [] #{J: 2, Par: 1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.1, m_max: 3.4, g_min: 0.001, g_max: 0.5,}
    Z3: [] #{J: 3, Par: -1, float: mg, m0: 2.9, g0: 0.10, m_min: 2.1, m_max: 3.4, g_min: 0.001, g_max: 0.5,}
    BpR_DPi:
        - D2_2460
        - D1_2600
        #- D0_2300
        #- D0_2900
        #- D3_2750
        #- D1_2760
        #- DJ_2640
        #- DJ_3000
        #- Dstar
    D1_2007: {J: 1, Par: -1, m0: 2.00685, g0: 0.0001, model: BW2007}

    NR_DPi0: [] #{display: "NR(0+)(D-pi+)", J: 0, P: 1, mass: 2.4, model: exp2}
    NR_DPi1: [] #{display: "NR(1-)(D-pi+)", J: 1, P: -1, mass: 2.4, model: one}
    DPi_S: {J: 0, P: 1, mass: 2.65, fix_idx: 4, model: spline_c, points: [1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 3.0, 3.2, 3.4]}
        #model: interp_hist, points: [1.95, 2.0, 2.05, 2.1, 2.15, 2.2, 2.25, 2.3, 2.35, 2.4, 2.42, 2.44, 2.46, 2.48, 2.5, 2.55, 2.6, 2.65, 2.7, 2.75, 2.85, 2.95, 3.05, 3.15, 3.25, 3.35]} #max_m: 3.35, min_m: 1.95, interp_N: 29}
    DPi_P: [] #{J: 1, P: -1, mass: 2.65, #model: interp_hist, max_m: 3.4, min_m: 2.0, interp_N: 15}
                #model: spline_c, points: [1.95, 2.05, 2.15, 2.25, 2.35, 2.45, 2.55, 2.65, 2.75, 2.85, 2.95, 3.05, 3.15, 3.25, 3.4]}
    Z0hist: [] #{J: 0, P: 1, mass: 2.970, model: interp_hist, points: [2.673,2.740,2.807,2.873,2.940,3.007,3.073,3.140,3.207]}#[2.693,2.759,2.824,2.890,2.956,3.021,3.087,3.153,3.219]}
    Z1hist: [] #{J: 1, P: -1, mass: 2.879, model: interp_hist, points: [2.525,2.614,2.702,2.791,2.879,2.968,3.056,3.145,3.234]}#[2.437,2.544,2.652,2.760,2.868,2.975,3.083,3.191,3.299]}

# constrains for params [WIP]
constrains:
    particle: null
    decay: {fix_chain_idx: 0, fix_chain_val: 1}


plot:
    # plot configuration TODO
    config:
        bins: 100
    # invariant mass
    mass:
        BpR_DDs:
            display: "$M_{D^-D_s^+}$"
            #legend: False
            #yscale: log
            #trans: x*x
        BpR_DPi:
            display: "$M_{D^-\\pi^+}$"
            #legend: False
            #yscale: log
            #trans: x*x
        BpR_DsPi:
            display: "$M_{D_s^+\\pi^+}$"
            #legend: False
            #yscale: log
            #trans: x*x
    angle:
        BpR_DPi/D:
            cos(beta):
                display: "$\\cos(\\theta^{D^-\\pi^+}_{D^-})$"
                range: [-1, 1]
                yscale: log
        BpR_DsPi/Ds:
            cos(beta):
                display: "$\\cos(\\theta^{D_s^+\\pi^+}_{D_s^+})$"
                range: [-1, 1]
                yscale: log
        BpR_DDs/D:
            cos(beta):
                display: "$\\cos(\\theta^{D^-D_s^+}_{D^-})$"
                range: [-1, 1]
                yscale: log
    # 2D plot
    2Dplot:
        m_BpR_DPi & m_BpR_DsPi:
            display: "$M_{D^-\\pi^+}^2$ vs $M_{D_s^+\\pi^+}^2$"
            trans: x*x
            plot_figs: [""]
    #    m_BpR_DsPi & m_BpR_DDs:
    #        display: "$M_{D_s^+\\pi^+}^2$ vs $M_{D^-D_s^+}^2$"
    #        plot_figs: ["data", "sideband"]
    #    m_BpR_DDs & m_BpR_DPi:
    #        display: "$M_{D^-D_s^+}^2$ vs $M_{D^-\\pi^+}^2$"
    #        plot_figs: ["data", "sideband"]



##### configC_Bp.yml

data:
    model: cfit
    dat_order: [D, Ds, Pi]
    bg_frac: [0.04399082735, 0.04362867728]
    data_bg_value: ["../dataDDspi/dat_cfit/BptoDmDspi_Data_Run1_value.dat", "../dataDDspi/dat_cfit/BptoDmDspi_Data_Run2_value.dat"]
    phsp_bg_value: ["../dataDDspi/dat_cfit/BptoDmDspi_MC_Run1_value.dat", "../dataDDspi/dat_cfit/BptoDmDspi_MC_Run2_value.dat"]
    #data_eff_value: "toy_data/data_eff_value.dat"
    #phsp_eff_value: "toy_data/phsp_eff_value.dat"

    data: [["../dataDDspi/dat/BptoDmDspi_Data_Run1.dat"], ["../dataDDspi/dat/BptoDmDspi_Data_Run2.dat"]]
    phsp: [["../dataDDspi/dat/BptoDmDspi_MC_Run1.dat"], ["../dataDDspi/dat/BptoDmDspi_MC_Run2.dat"]]
    phsp_weight: ["../dataDDspi/dat/BptoDmDspi_MC_Run1_Weight.dat", "../dataDDspi/dat/BptoDmDspi_MC_Run2_Weight.dat"]
    phsp_noeff: ["../dataDDspi/dat/BptoDmDspi_MC_Noeff.dat"]
    cached_amp: True
    bg: [["../dataDDspi/dat_cfit/BptoDmDspi_Run1_BKGsample.dat"], ["../dataDDspi/dat_cfit/BptoDmDspi_Run2_BKGsample.dat"]]
    bg_weight: [0.030461068114682886, 0.037890282591876205] # note the sample data has changed. need to scp from lxplus.cern.ch
